# Welcome to Mei Rusfandi Profile's
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Mei Rusfandi Profile's
email: meirusfandi100@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Pascal Programmer - Trainer of Programming - Android Developer - C++ Programmer
baseurl: "/profile" # the subpath of your site, e.g. /blog
url: "http://meirusfandi.github.io" # the base hostname & protocol for your site

# Social media profiles - feel free to add more here
twitter_username: @rf_mei
github_username:  meirusfandi
facebook_username: meirusfandi
#instagram_username: meirusfandi
#stackoverflow_url: http://stackoverflow.com/users/6924347/mei-rusfandi
#googleplus_username: Mei Rusfandi
#linkedin_url: https://www.linkedin.com/in/mei-rusfandi-a95454128?trk=nav_responsive_tab_profile

# Address information
address_street: Jalan Kediri, Kecamatan Gadingrejo, Pringsewu
address_city: Pringsewu
address_state: INA
address_zip: 35372

# Build settings
markdown: kramdown
